extra:
  author: komiyamma
  author_alternate: こみやんま
  author_sameas:
    - https://x.com/komiyamma
    - https://github.com/komiyamma
site_name: My MkDocs Site
nav:
  - ホーム: index.md
  - プログラミング:
    - Python入門: python_intro.md
    - JavaScript基礎: js_basics.md
    - Web開発の流れ: web_flow.md
    - Gitの使い方: git_usage.md
  - ライフハック:
    - 時間管理術: time_management.md
    - 片付けのコツ: cleaning_tips.md
    - 効率的な勉強法: study_tips.md
    - 目標設定の方法: goal_setting.md
  - テクノロジー:
    - AIの基礎: ai_basics.md
    - クラウドとは: cloud_intro.md
    - IoT入門: iot_intro.md
    - サイバーセキュリティ: cyber_security.md
theme:
  name: material
  custom_dir: overrides
plugins:
  - search:
      lang:
        - ja
        - en
  - description_from_memo:
