extra:
  author: komiyamma
  author_alternate: こみやんま
  author_sameas:
    - https://x.com/komiyamma
    - https://github.com/komiyamma
  default_image: assets/images/default_ogp.png
site_name: My MkDocs Site
theme:
  name: material
  custom_dir: overrides
plugins:
  - search:
      lang:
        - ja
        - en
  - description_from_memo
  - awesome-pages
